...

diff --git a/dot b/dot
--- a/dot
+++ b/dot
@@ -2,9 +2,39 @@
 
 function dot() {
     local CONFIG_FILE="${BASH_SOURCE%/*}/yml/dot.yml"
+    function dot_help(){
+        echo "
+DESCRIPTION:
+    Navigate in directory stack, and open and execute files.
+
+USAGE:
+    dot [option] [argument]
+
+OPTIONS:
+    n, nav [dir] ............ Navigate to the specified directory and list contents
+           [file] ........... Open the specified file according to its extension
+           '-', '...' ....... Go back to the previous directory in the stack
+           '..' ............. Navigate to parent directory
+    h, home [user] .......... Navigate to the user's home directory
+    a, alias ................ Navigate or open alias directory or file
+    s, src, source .......... Source a file or all files in a directory
+    x, exec.................. Execute the file according to its extension
+    p, preview .............. Open fzf in preview mode for the given directory
+    d, delete ............... Safely delete the given entry
+    l, ls, list ............. List files and directories
+    lf, lsf, list-files ..... List files
+    ld, lsd, list-dirs ...... List dirs
+    rm, remove .............. Permanently remove the given entry
+    rn, rename .............. Rename the given entry
+    rc, rc .................. Open some rc file with given alias
+    mf, mkf, make-file ...... Create files
+    md, mkd, make-dir ....... Create directories
+    t, template ............. Instantiate a template
+    "
+    }
 
     function dot_ls(){
-        if [[ "$1" == "hidden" ]]; then
+        if [[ "$1" == "h" ]]; then
             if [[ -n "$DOT_LS_HIDDEN" ]]; then
                 shift 1
                 "$DOT_LS_HIDDEN" "$@"
@@ -20,7 +50,7 @@ function dot() {
         fi
     }
 
-    function dot_nav() {
+    function dot_cd() {
         if [[ -n "$DOT_CD" ]]; then
             "$DOT_CD" "$@"
         else
@@ -35,40 +65,29 @@ function dot() {
         eval "$cmd $1"
     }
 
+    function dot_nav(){
+        if [[ "$1" == "-" || "$1" == "..." ]]; then
+            shift 1
+            popd > /dev/null 2>&1
+            dot_ls "$@"
+        elif [[ "$1" == ".." ]]; then
+            cd ..
+        elif [[ -d "$1" ]]; then
+            dot_cd "$1"
+            dot_ls
+        elif [[ -f "$1" ]]; then
+            dot_open "$1"
+        else
+            dot_ls
+        fi
+    }
+
     function dot_exec() {
         local ext=${1##*.}
         local cmd=$(yq e ".exec.${ext} $CONFIG_FILE")
         if [[ -n "$cmd" ]]; then
             eval "$cmd "$1""
         fi
-    }
-
-    function dot_help(){
-        echo "
-
-DESCRIPTION:
-    Navigate in directory stack, and open and execute files.
-
-USAGE:
-    dot [option] [argument]
-
-OPTIONS:
-    [dir] ...................... Navigate to the specified directory and list contents
-    [file] ..................... Open the specified file according to its extension
-    -, ... ..................... Go back to the previous directory in the stack
-    .. ......................... Navigate to parent directory
-    -h, --home [user] .......... Move to the user's home directory
-    -c, --config [alias] ....... Move to the config directory with given alias
-    -r, --rc [alias] ........... Open rc file with given alias
-    -a, --alias [alias] ........ Navigate or open alias directory or file
-    -s, --src [file] ........... Source the file
-    -x, --exec [file] .......... Execute the file according to its extension
-    -p, --preview [dir] ........ Open fzf in preview mode for the given directory
-    -n, --name [entry].......... Rename the given entry
-    -d, --delete [entry] ....... Safely delete the given entry
-    -rm, --remove [entry] ...... Permanently remove the given entry
-
-    "
     }
 
     function dot_home(){
@@ -85,8 +104,15 @@ OPTIONS:
         fi
     }
 
+    function dot_trash(){
+        TRASH_DIR=$(yq e ".trash.path" $CONFIG_FILE)
+        if [[ -z "$TRASH_DIR" || "$TRASH_DIR" == "null" ]]; then
+            TRASH_DIR=$HOME/.trash
+        fi
+    }
+
     function clean_trash() {
-        TRASH_DIR=$(yq e ".trash.path // \"$HOME/.trash\"" $CONFIG_FILE)
+        dot_trash
         local CLEAN_TIME_DAYS=$(yq e '.trash.clean.time // 30' $CONFIG_FILE)
         local CLEAN_SIZE_MB=$(yq e '.trash.clean.size' $CONFIG_FILE)
         find "$TRASH_DIR" -type f -mtime +$CLEAN_TIME_DAYS -exec rm {} \;
@@ -101,6 +127,7 @@ OPTIONS:
     }
 
     function dot_del(){
+        dot_trash
         TRASH_LOG="$TRASH_DIR/trash.log"
         clean_trash
         if [[ ! -f "$TRASH_LOG" ]]; then
@@ -125,9 +152,14 @@ OPTIONS:
     }
 
     function dot_rm(){
-        if [[ -e "$1" ]]; then
-            rm -rf "$1"
-        fi
+        for i in "$@"; do
+            if [[ -e "$i" ]]; then
+                rm -rf "$i"
+            else
+                echo "error: \"$1\" does not exists."
+                return
+            fi
+        done
     }
 
     function dot_config(){
@@ -151,18 +183,66 @@ OPTIONS:
             fi
         fi
     }
+    function dot_template(){ 
+        echo "to be added..."
+    }
     
-    function dot_alias(){
-        local alias_path=$(yq e ".paths.alias.dirs.${2} // .paths.alias.files.${2}" $CONFIG_FILE)
-        if [[ -n "$alias_path" ]]; then
-            if [[ -d "$alias_path" ]]; then
-                cd "$alias_path"
-            elif [[ -f "$alias_path" ]]; then
-                dot_open "$alias_path"
+
+   function dot_alias() {
+        if [[ -z "$2" ]]; then
+            local alias_input="${1}"
+        else
+            alias_input=${!#}
+        fi
+        alias_stack=()
+        for ((i = 1; i < $#; i++)); do
+            alias_stack+=("${!i}")
+        done
+        local alias_name="${alias_input%%/*}"
+        local remainder_path="${alias_input#*/}"
+        if [[ -z "$2" ]]; then
+            alias_string=$alias_name
+        else
+            alias_string="${alias_stack[*]}.$alias_name"
+            alias_string=${alias_string// /.}
+        fi
+        if [[ "$alias_input" == "$alias_name" ]]; then
+            remainder_path=""
+        fi
+        echo $alias_string
+
+        local alias_dir=$(yq eval ".alias.${alias_string}.path" "$CONFIG_FILE")
+        local recursive=$(yq eval ".alias.${alias_string}.recursive // false" "$CONFIG_FILE")
+        local depth=$(yq eval ".alias.${alias_string}.depth // 0" "$CONFIG_FILE")
+
+        if [[ ! -d "$alias_dir" ]]; then
+            echo "Error: Alias or base directory not valid."
+            return
+        fi
+
+        if [[ -z "$remainder_path" ]]; then
+            dot_nav "$alias_dir"
+            return
+        fi
+
+        local target_path="$alias_dir/$remainder_path"
+
+        if [[ -d "$target_path" ]]; then
+            dot_nav "$target_path"
+            return
+        fi
+
+        if [[ "$recursive" == "true" && "$depth" -ge 0 ]]; then
+            local search_path=$(find "$alias_dir" -mindepth 1 -maxdepth "$depth" -type d -path "$target_path*" -print -quit)
+            if [[ -d "$search_path" ]]; then
+                dot_nav "$search_path"
+                return
             fi
         fi
-    }
 
+        echo "Error: '$target_path' is not a valid directory."
+    }
+ 
     function dot_preview(){
         if [[ -n $(which fzf) ]]; then
             fzf --preview="cat {}"
@@ -170,69 +250,143 @@ OPTIONS:
     }
 
     function dot_source(){
-        if [[ -f "$1" ]]; then
-            source $1
+        if [[ -z "$1" ]]; then
+            source $HOME/.bashrc
+        else
+            for i in $@; do
+                if [[ -f "$i" ]]; then
+                    source $i
+                elif [[ -d "$i" ]]; then
+                    find $i -type f -exec source {} \;
+                else
+                    echo "error: \"$i\" does not exists."
+                    return 1
+                fi
+            done 
         fi
     }
 
-    function dot_name(){
+    function dot_rename(){
         if [[ -e "$1" ]] && [[ -n "$2" ]]; then
             mv "$1" "$2"
         fi
     }
 
-    if [[ -z "$1" || "$1" == "-l" || "$1" == "--ls" ]]; then
-        shift 1
-        dot_ls "$@"
-    elif [[ "$1" == "--help" ]]; then
-        dot_help
-    elif [[ "$1" == "--hidden" ]]; then
-        shift 1
-        dot_ls hidden "$@"
-    elif [[ -d "$1" ]]; then
-        dot_nav "$@"
-        dot_ls "$@"
-    elif [[ "$1" == "-" || "$1" == "..." ]]; then
-        shift 1
-        popd > /dev/null 2>&1
-        dot_ls "$@"
-    elif [[ "$1" == ".." ]]; then
-        cd ..
-    elif [[ "$1" == "-h" || "$1" == "--home" ]]; then
-        shift 1
-        dot_home "$@"    
-    elif [[ "$1" == "-c" || "$1" == "--config" ]]; then
-        shift 1
-        dot_config "$@"
-    elif [[ "$1" == "-rc" || "$1" == "--rc" ]]; then
-        shift 1
-        dot_rc "$@"
-    elif [[ "$1" == "-a" || "$1" == "--alias" ]]; then
-        shift 1
-        dot_alias "$@"
-    elif [[ "$1" == "-s" || "$1" == "--source" ]]; then
-        shift 1
-        dot_source "$@"
-    elif [[ "$1" == "-x" || "$1" == "--exec" ]]; then
-        shift 1
-        if [[ -f "$2" ]]; then 
-            dot_exec $2
+    function dot_mk(){
+        if [[ "$1" == "file" || "$1" == "f" ]]; then
+            shift 1
+            touch "$@"
+        elif [[ "$1" == "dir" || "$1" == "d" ]]; then
+            shift 1
+            mkdir "$@"
+        else
+            echo "error: option not defined."
+            return 1
         fi
-    elif [[ "$1" == "-p" || "$1" == "--preview" ]]; then
-        shift 1
-        dot_preview "$@"
-    elif [[ "$1" == "-n" || "$1" == "--name" ]]; then
-        shift 1
-        dot_name "$@"
-    elif [[ "$1" == "-d" || "$1" == "--delete" ]]; then
-        shift 1
-        dot_del "$@"
-    elif [[ "$1" == "-rm" || "$1" == "--remove" ]]; then
-        shift 1
-        dot_rm "$@"
-    elif [[ -f "$1" ]]; then
-        dot_open $1
-    else
-        dot_help
-    fi
+    }
+
+    case "$1" in
+        "")
+            dot_help 
+            ;;
+        help|--help)
+            dot_help
+            ;;
+        n|nav)
+            shift 1
+            dot_nav "$@"
+            if [[ "$?" == "1" ]]; then
+                return 1
+            fi
+            ;;
+        l|ls)
+            shift 1
+            dot_ls "$@"
+            if [[ "$?" == "1" ]]; then
+                return 1
+            fi
+            ;;
+        h|home)
+            shift 1
+            dot_home "$@"
+            if [[ "$?" == "1" ]]; then
+                return 1
+            fi
+            ;;
+        o|open)
+            shift 1
+            dot_open "$@"
+            if [[ "$?" == "1" ]]; then
+                return 1
+            fi
+            ;;
+        x|exec)
+            shift 1
+            dot_exec "$@"
+            if [[ "$?" == "1" ]]; then
+                return 1
+            fi
+            ;;
+        rc)
+            shift 1
+            dot_rc "$@"
+            if [[ "$?" == "1" ]]; then
+                return 1
+            fi
+            ;;
+        a|alias)
+            shift 1
+            dot_alias "$@"
+            if [[ "$?" == "1" ]]; then
+                return 1
+            fi
+            ;;
+        p|preview)
+            shift 1
+            dot_preview "$@"
+            if [[ "$?" == "1" ]]; then
+                return 1
+            fi
+            ;;
+        rn|rename)
+            shift 1
+            dot_rename "$@"
+            if [[ "$?" == "1" ]]; then
+                return 1
+            fi
+            ;;
+        rm|remove)
+            shift 1
+            dot_remove "$@"
+            if [[ "$?" == "1" ]]; then
+                return 1
+            fi
+            ;;
+        d|del|delete)
+            shift 1
+            dot_del "$@"
+            if [[ "$?" == "1" ]]; then
+                return 1
+            fi
+            ;;
+        m|mk|make)
+            shift 1
+            dot_mk "$@"
+            ;;
+        mf|mkf|make-file)
+            shift 1
+            dot_mk file "$@"
+            ;;
+        md|mkd|make-dir)
+            shift 1
+            dot_mk dir "$@"
+            ;;
+        t|template)
+            shift 1
+            dot_template "$@"
+            ;;
+        *)
+            dot_help
+            ;;
+    esac
 }
